# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 南阳理工学院开源软件镜像站
school: 南阳理工学院
brand: NYIST Open Source Mirror
operator: 南阳理工学院信息化建设与管理中心
author: Tsinghua University TUNA Association
desc: 南阳理工学院开源镜像站由我校NYIST-CIPS维护，收录了大量开源镜像供校内外用户使用，用以支持我校的软件教育与教学工作。
logo: true
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirror.nyist.edu.cn/"
hostname: "mirror.nyist.edu.cn/"
urlv4: "https://mirror4.nyist.edu.cn/"
urlv6: "https://mirror6.nyist.edu.cn/"
aosp: "aosp.mirror.nyist.edu.cn" #这里需要再help目录下创建/AOSP
arch_archive: "arch-archive.tuna.tsinghua.edu.cn" #arch_archive 目录
pypi: "pypi.tuna.tsinghua.edu.cn" #pipy 目录
homelink: "https://github.com/NYIST-CIPS/" #主页还没有 暂时github的链接
hide_navbar: false
hide_download: false
hide_server_status: false

hide_mirrorz: false
mirrorz_desc: 校园网联合镜像站
mirrorz_link: "https://mirrors.cernet.edu.cn/list"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

plugins:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

sponsors:
    megvii:
        name: "旷视科技有限公司"
        link: "https://megvii.com/"
        short: "旷视"
        eng: "Megvii Technology Ltd."
        logo: "megvii-s"
    huawei:
        name: "华为技术有限公司"
        link: "https://huawei.com/"
        short: "华为"
        eng: "Huawei Technologies Co., Ltd."
        logo: "huawei"

poweredbys:
    kunpeng: "海思<sup>®</sup> Kunpeng<sup>®</sup> 920 处理器"

# vim: ts=2 sts=2 sw=2 expandtab
