name: docker-images

on:
  push:
    branches: 
    - master
    - docker-test
  pull_request:
    branches: 
    - master
    - docker-test

jobs:
  multi:
            
    runs-on: ubuntu-latest
    steps:
      -
        name: Send start notification to WeCom
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
        with:
          msgtype: text
          content: "NYIST/mirror-web 测试构建已开始🚀"
      - 
        name: Determin docker tag
        env:
          TAG_NAME: ${{ github.ref }}
        run: |
          if [ "${TAG_NAME##*/}" = "master" ]; then
            tag=latest
          else
            tag=build-test
          fi
          echo "docker_tag=${tag}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Prevent from loading rubygems from TUNA
        run: |
          sed -i "/^source/c source 'https://rubygems.org'" Gemfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        if: github.event_name == 'push'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-mirrorweb-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-mirrorweb-
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        if: github.event_name == 'pull_request'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-mirrorweb-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-mirrorweb-
            ${{ runner.os }}-buildx-mirrorweb-
      -
        name: Cache Docker layers
        if: github.event_name != 'push' && github.event_name != 'pull_request'
        run: |
          echo "I do not know how to setup cache"
          exit -1
      -
        name: Send end notification to WeCom
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
        with:
          msgtype: text
          content: "NYIST/mirror-web 测试构建完成，请部署前端至服务器"
